### ISSUE TITLE
Cannot add property onClick, object is not extensible

### ISSUE THREAD

**Issue by HyperMaxime** [vaheqelyan/react-awesome-popover#1]
Hi, 

I tried to use this library but immediately got this error: 
> Cannot add property onClick, object is not extensible

After googling I found this on the release notes of React:
> The props object is now frozen, so mutating props after creating a component element is no longer supported. In most cases, React.cloneElement should be used instead. This change makes your components easier to reason about and enables the compiler optimizations mentioned above. - [link](https://reactjs.org/blog/2015/10/07/react-v0.14.html#breaking-changes)

Kind regards

**Comment by vaheqelyan** [comment]
@HyperMaxime can you provide your code, please?

**Comment by vaheqelyan** [comment]
Hi @HyperMaxime. Could you provide your code or link to jsfiddle or i do not know something else.
In this [jsfiddle](https://jsfiddle.net/vaheqelyan/x48ph3zp/) i am using version 0.14.0,but still i did not get any errors, i guess you are using [ReactJS 0.14.0](https://github.com/facebook/react/blob/master/CHANGELOG.md#0140-october-7-2015)

**Comment by HyperMaxime** [comment]
Hi @vaheqelyan,

The production build of react doesn't show these errors, but they are there in the development build.
I updated your jsfiddle to have the development build of react and react-dom so you can see the errors in the console: [link](https://jsfiddle.net/x48ph3zp/1/).

**Comment by vaheqelyan** [comment]
check it out -> [jsfiddle](https://jsfiddle.net/vaheqelyan/x48ph3zp/3/)
The `Object.preventExtensions()` method prevents the new property onClick.
https://github.com/vaheqelyan/react-awesome-popover/commit/1c6537bd95048465ba1b5d5d0639fda032b88127#diff-6b9279395755e9b3797ccf623cc31aabL33

**Comment by vaheqelyan** [comment]
I'm closing this issue, feel free to reopen
