### ISSUE TITLE
JSFiddle doesn't exist

### ISSUE THREAD

**Issue by vanessa** [vaheqelyan/react-awesome-popover#12]
Accessing the [JSFiddle url](https://jsfiddle.net/vaheqelyan/6qogfdkr/36/show/light/) given as demo returns a 404 error.

**Comment by vaheqelyan** [comment]
You are right.

The URL should be http://jsfiddle.net/vaheqelyan/6qogfdkr/36/embedded/result/ instead of https://jsfiddle.net/vaheqelyan/6qogfdkr/36/show/light/

**Comment by pmiddend** [comment]
Can you fix this in the README so people know how to use your component? :)
