### ISSUE TITLE
action={null} is not working for controlled component

### ISSUE THREAD

**Issue by BrunoQuaresma** [vaheqelyan/react-awesome-popover#15]
Even using action={null} and the open props the popover is displaying by the hover action.
eg.
```
<Popover action={null} open={isPopoverOpen}>
...
</Popover>
```

**Comment by vaheqelyan** [comment]
Is this ok?
![](https://res.cloudinary.com/dmtrk3yns/image/upload/q_auto/v1548408927/ezgif-4-02daa3dc4096_xdpjgp.gif)

**Comment by BrunoQuaresma** [comment]
Sorry for delay. It is, thanks for that.
