### ISSUE TITLE
Popper.js version

### ISSUE THREAD

**Issue by ThomBian** [vaheqelyan/react-awesome-popover#17]
Current behavior: 
The actual dependency to `popper.js` is marked as `^.0.7.4` and installs popper.js in version `0.7.5`

Expected behavior:
upgrade dependency to use only `0.7.4` or `8.0.0 or above`. It seems that popper.js `0.7.5` has a huge performance issue

Thanks!

**Comment by vaheqelyan** [comment]
i will try to upgrade tomorrow

**Comment by vaheqelyan** [comment]
I need to rewrite the component, I will release a new version when I have a little more time

**Comment by vaheqelyan** [comment]
Sorry for the delay. I still maintain this component. I'm just checking to see if everything's okay. Today or tomorrow I will publish a new release. react-popper@1.3.3.

**Comment by vaheqelyan** [comment]
I'm just checking to see if everything's okay.

![](https://res.cloudinary.com/dmtrk3yns/image/upload/q_auto/v1554978707/ezgif.com-video-to-gif_1_mxrd0r.gif)

![](https://res.cloudinary.com/dmtrk3yns/video/upload/q_auto/v1554978603/ice_video_20190411-142659_yi6dcl.gif)

**Comment by vaheqelyan** [comment]
I have released a new version
Note. ![What about the arrow](https://github.com/vaheqelyan/react-awesome-popover#what-about-the-arrow)
