### ISSUE TITLE
Suggestion: mention polyfill to readme for IE support

### ISSUE THREAD

**Issue by HyperMaxime** [vaheqelyan/react-awesome-popover#2]
Hi,

I noticed that the popover does not show up in IE, due to the experimental Element.closest() method being used in the codebase.

A simple polyfill overcomes this issue:
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill&features=Element.prototype.closest"></script>`

This could be mentioned in the readme file.

Kind regards,
Maxime

**Comment by vaheqelyan** [comment]
Yeah you are right. I will include a polyfill, but a little later

**Comment by vaheqelyan** [comment]
included polyfill in version 1.5.0 https://github.com/vaheqelyan/react-awesome-popover/commit/3f55383f8987a139f326fb558c15b8ac02b3c403
