### ISSUE TITLE
Cannot set positionFixed

### ISSUE THREAD

**Issue by valtism** [vaheqelyan/react-awesome-popover#20]
Would love to have it so that the popover can pop over elements and not move itself to try to fit within its container. This can be achieved by exposing popper.js's positionFixed property to true.

**Comment by vaheqelyan** [comment]
Sure

**Comment by vaheqelyan** [comment]
Update react-awesome-popover@4.1.0. Hopefully this should be fixed

 Feel free to reopen :)

**Comment by valtism** [comment]
Wow, thanks for such a quick response and turnaround!
