### ISSUE TITLE
Placement variations have unexpected render outcomes.

### ISSUE THREAD

**Issue by HyperMaxime** [vaheqelyan/react-awesome-popover#5]
Hi,

In my application I want a popover with arrow that is aligned to the bottom right of the button.
From your codebase I understand that you leverage on Popper.js, which has the "bottom-end" placement option for that use case. When using that here, it has a broken outcome: https://jsfiddle.net/x48ph3zp/5/

It would be nice if that problem could be solved.
Thank you in advance!

**Comment by vaheqelyan** [comment]
[https://jsfiddle.net/vaheqelyan/x48ph3zp/7/](https://jsfiddle.net/vaheqelyan/x48ph3zp/7/)
https://github.com/vaheqelyan/react-awesome-popover/commit/e6097b560768338fdf8b51d10a7afbfa92bf270d
https://github.com/vaheqelyan/react-awesome-popover/commit/1b99a3f0b7eea41b82202da93836f5615b2587f4#diff-2edd0552352f67d6befd96bb0839cd34R95
has this fixed the problem? I'll work on it later, but anyway, let's keep this issue open

**Comment by HyperMaxime** [comment]
Perfect, thanks a lot for the quick solution!
