### ISSUE TITLE
Feature request: possibility to close popover programmatically

### ISSUE THREAD

**Issue by HyperMaxime** [vaheqelyan/react-awesome-popover#6]
Hi,

The use case I have is a popover controlling the sorting of a result page.
![image](https://user-images.githubusercontent.com/24253436/33212585-2e1cbfb2-d124-11e7-98d8-2432afba3038.png)
Clicking in the popover on another sorting preference triggers the fetching and rendering of the newly sorted results (and only that section of the page).

Currently the popover stays open until clicked outside of it. It would make more sense to close the popover after clicking on another sorting option. I do not know a way of doing this with the current api.

Any ideas about how I can achieve this?

Kind regards

**Comment by vaheqelyan** [comment]
[http://jsbin.com/vuhavuw/2/edit?html,js,output](http://jsbin.com/vuhavuw/2/edit?html,js,output)
isOpen  → defaultIsOpen
open  → Passing this prop puts the popover in controlled mode

I will wait for your review @HyperMaxime 
But the close button does not work inside the contents of the popover, i will try to solve this problem.

**Comment by vaheqelyan** [comment]
I know this is not the way to close a popover programmatically, but it works.You can click outside of popover.
```javascript
...
onFilter(){
 ....
document.body.click(); // <--- when you need to close the popover
 ...
}
...
```

**Comment by HyperMaxime** [comment]
Hi, thank you for the response.
The close button not working from within the Popover component is indeed an issue.
I tried setting the state through onClick to reflect that the popover opened after clicking on the anchor element, but that did not happen which lead to the close button not doing anything (since the isOpen prop is still false).

For my use case, I could get the desired outcome with a small 'hack' more or less like this: http://jsbin.com/tirohaxura/edit?css,js,output

However, I don't think it is a good solution and would prefer having the first approach work.

Kind regards, Maxime

**Comment by vaheqelyan** [comment]
@HyperMaxime I used the wrong life cycle. Maybe the simple change will fix everything

```javascript
  componentWillReceiveProps({open}) {
    this.setState({isOpen:open})
  }
```
instead of this
```javascript
 componentDidUpdate(prevProps, prevState) {
    if (this.props.open !== prevProps.open) {
      this.setState({ isOpen: this.props.open });
    }
  }
```
<img src="https://res.cloudinary.com/dxv8p5zck/video/upload/v1512033007/ice_video_20171130-130734_xbzvg4.gif"/>

**Comment by vaheqelyan** [comment]
i close this issue
[react-awesome-popover@1.6.1](https://unpkg.com/react-awesome-popover@1.6.1/dest/react-awesome-popover.js)
```javascript
class Popover1 extends React.Component {
  constructor(props){
    super();
    this.state = {isOpen:false}
  }
  render() {
    return (
      <div className="container">

      <button onClick={()=>this.setState({isOpen:true})}>Open</button>
      <button onClick={()=>this.setState({isOpen:false})}>Close</button>
        
        <Popover action="click" placement="bottom" open={this.state.isOpen} >
          <a>Click</a>
          <div>
            <h1>Hello world</h1>
            <button onClick={()=>this.setState({isOpen:false})}>
              Close
            </button>
          </div>
        </Popover>
      </div>
    );
  }
}
```
