### ISSUE TITLE
Issues with Server Side Rendering 

### ISSUE THREAD

**Issue by sheerun** [vaheqelyan/react-awesome-popover#8]
Because you use "window" in code it's not possible to render Popover on server side without conditionally not renderring it at all. Ideally on server side it would render just trigger element, and then bind popover to it in componentDidMount()

**Comment by vaheqelyan** [comment]
Hi @sheerun.In fact, I'm going to release a new major version of the package.I will also fix the ssr problem.

**Comment by vaheqelyan** [comment]
I rewrote the API and also solved some problems with server-side rendering.Update the package version to v2.0.2
